{
    imports = [
        ./bash.nix
        ./btop.nix
        ./cava.nix
        ./fastfetch.nix
        ./firefox.nix
        ./fuzzel.nix
        ./hyprland.hypridle.nix
        ./hyprland.hyprlock.nix
        ./hyprland.hyprshot.nix
        ./hyprland.nix
        ./kitty.nix
        ./mako.nix
        ./micro.nix
        ./spotify-player.nix
        ./theme.nix
        ./vesktop.nix
        ./vscodium.nix
        ./waybar.nix
        ./wayland-clipboard.nix
    ];
}